CREATE TABLE IF NOT EXISTS "app_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(64) NOT NULL UNIQUE,
    "password" VARCHAR(256) NOT NULL,
    "role" VARCHAR(32) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE IF NOT EXISTS "order_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(64) NOT NULL UNIQUE,
    "price" INT NOT NULL,
    "quantity" INT NOT NULL,
    "description" TEXT NOT NULL,
    "supplier" VARCHAR(64) NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("supplier") REFERENCES "app_users"("username") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" VARCHAR(64) NOT NULL,
    "discount" INT,
    "total_sum" INT,
    "address" VARCHAR(8192) NOT NULL,
    "order_date" DATE NOT NULL DEFAULT current_date,
    CONSTRAINT fk_user FOREIGN KEY ("user") REFERENCES "app_users"("username") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "orders_order_item" (
    "order_id" BIGINT NOT NULL,
    "order_item_id" BIGINT NOT NULL,
    PRIMARY KEY ("order_id", "order_item_id"),
    CONSTRAINT fk_orders FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE,
    CONSTRAINT fk_order_items FOREIGN KEY ("order_item_id") REFERENCES "order_item"("id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "payments"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" VARCHAR(64) NOT NULL,
    "date_payment" DATE NOT NULL DEFAULT current_date,
    "order_id" BIGINT NOT NULL,
    "payment_method" VARCHAR(64) NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("user") REFERENCES "app_users"("username") ON DELETE CASCADE,
    CONSTRAINT fk_order_id FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
);
