CREATE TABLE IF NOT EXISTS "app_users" (
                                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "username" VARCHAR(64) NOT NULL UNIQUE,
    "password" VARCHAR(128) NOT NULL,
    "role" VARCHAR(32) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE'
    );

-- Наполнение базовыми данными (Flyway выполнит это один раз при создании таблицы)
INSERT INTO "app_users" ("username", "password", "role", "status")
VALUES
    ('admin', 'admin123', 'ADMIN', 'AVAILABLE'),
    ('user', 'user123', 'USER', 'AVAILABLE'),
    ('supplier', 'supplier123', 'SUPPLIER', 'AVAILABLE'),
    ('courier', 'courier123', 'COURIER', 'AVAILABLE')
    ON CONFLICT ("username") DO NOTHING;

CREATE TABLE IF NOT EXISTS "order_item" (
                                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            "name" VARCHAR(64) NOT NULL UNIQUE,
    "price" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "supplier" VARCHAR(64) NOT NULL,
    CONSTRAINT fk_order_item_supplier FOREIGN KEY ("supplier") REFERENCES "app_users"("username") ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS "orders" (
                                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "user_username" VARCHAR(64) NOT NULL, -- Переименовано из "user", чтобы избежать конфликтов с синтаксисом SQL
    "discount" INT,
    "total_sum" INT,
    "address" VARCHAR(8192) NOT NULL,
    "order_date" DATE NOT NULL DEFAULT current_date,
    CONSTRAINT fk_orders_customer FOREIGN KEY ("user_username") REFERENCES "app_users"("username") ON DELETE CASCADE
    );

CREATE INDEX idx_orders_users_id ON "orders"("user_username");

CREATE TABLE IF NOT EXISTS "orders_order_item" (
                                                   "order_id" BIGINT NOT NULL,
                                                   "order_item_id" BIGINT NOT NULL,
                                                   PRIMARY KEY ("order_id", "order_item_id"),
    CONSTRAINT fk_ooi_orders FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE,
    CONSTRAINT fk_ooi_order_items FOREIGN KEY ("order_item_id") REFERENCES "order_item"("id") ON DELETE CASCADE
    );

CREATE INDEX idx_orders_order_item_item_id ON "orders_order_item"("order_item_id");

CREATE TABLE IF NOT EXISTS "payments"(
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "user_username" VARCHAR(64) NOT NULL,
    "date_payment" DATE NOT NULL DEFAULT current_date,
    "order_id" BIGINT NOT NULL,
    "payment_method" VARCHAR(64) NOT NULL,
    CONSTRAINT fk_payments_users FOREIGN KEY ("user_username") REFERENCES "app_users"("username") ON DELETE CASCADE,
    CONSTRAINT fk_payments_orders FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
    );


CREATE TABLE IF NOT EXISTS "orders_couriers" (
                                                 "order_id" BIGINT NOT NULL,
                                                 "courier_username" VARCHAR(64) NOT NULL,
    "status" VARCHAR(64) DEFAULT 'start',
    "code" BIGINT DEFAULT floor(random() * (999999 - 100000 + 1) + 100000)::BIGINT,
    PRIMARY KEY ("order_id", "courier_username"),
    CONSTRAINT fk_oc_orders FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE,
    CONSTRAINT fk_oc_couriers FOREIGN KEY ("courier_username") REFERENCES "app_users"("username") ON DELETE CASCADE
    );

CREATE INDEX idx_orders_couriers_courier ON "orders_couriers"("courier_username");


INSERT INTO "app_users" ("username", "password", "role", "status")
VALUES
    ('admin', 'admin123', 'ADMIN', 'AVAILABLE'),
    ('user', 'user123', 'USER', 'AVAILABLE'),
    ('supplier', 'supplier123', 'SUPPLIER', 'AVAILABLE'),
    ('courier', 'courier123', 'COURIER', 'AVAILABLE')
    ON CONFLICT ("username")
DO NOTHING;